feat(cli): Implement error handling for cli encryptor parsing
In the main loop of iggy-cli, putting invalid value for encryptor will
generate a panic from client side, however, a panic should refer to a
programmer bug rather than invalid user input.

Implement error handling when facing invalid user input of encryptor
for iggy-cli, which will output an error message, e.g.
```
Error: CommandError(Iggy command line tool error

Caused by:
    Invalid encryption key provided)
```

Signed-off-by: I Hsin Cheng <richard120310@gmail.com>